-- MySQL Script generated by MySQL Workbench
-- Mon Apr 26 17:05:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WeatherDataStore
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `WeatherDataStore` ;

-- -----------------------------------------------------
-- Schema WeatherDataStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WeatherDataStore` DEFAULT CHARACTER SET utf8 ;
USE `WeatherDataStore` ;

-- -----------------------------------------------------
-- Table `WeatherDataStore`.`Contributer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WeatherDataStore`.`Contributer` ;

CREATE TABLE IF NOT EXISTS `WeatherDataStore`.`Contributer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `active` BIT(1) NOT NULL DEFAULT 1,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WeatherDataStore`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WeatherDataStore`.`Country` ;

CREATE TABLE IF NOT EXISTS `WeatherDataStore`.`Country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WeatherDataStore`.`Circuit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WeatherDataStore`.`Circuit` ;

CREATE TABLE IF NOT EXISTS `WeatherDataStore`.`Circuit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `API_id` VARCHAR(45) NULL,
  `name` VARCHAR(60) NOT NULL,
  `countryID` INT NOT NULL,
  `lat` DECIMAL(10,8) NOT NULL,
  `long` DECIMAL(11,8) NOT NULL,
  `Locality` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `country_idx` (`countryID` ASC) VISIBLE,
  CONSTRAINT `country`
    FOREIGN KEY (`countryID`)
    REFERENCES `WeatherDataStore`.`Country` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WeatherDataStore`.`Weather`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WeatherDataStore`.`Weather` ;

CREATE TABLE IF NOT EXISTS `WeatherDataStore`.`Weather` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `weatherStation` VARCHAR(20) NOT NULL,
  `time` DATETIME NULL,
  `airTemp` FLOAT NULL,
  `dewPoint` FLOAT NULL,
  `relativeHumidity` INT NULL,
  `hourTotalPrecipitation` FLOAT NULL,
  `snowDepth` INT NULL,
  `windDirection` INT NULL,
  `avgWindSpeed` FLOAT NULL,
  `peakWindGust` FLOAT NULL,
  `airPressure` FLOAT NULL,
  `hourTotalSunshine` INT NULL,
  `conditionCode` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WeatherDataStore`.`Round`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WeatherDataStore`.`Round` ;

CREATE TABLE IF NOT EXISTS `WeatherDataStore`.`Round` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `circuitID` INT NOT NULL,
  `weatherID` INT NULL,
  `quarter` INT NOT NULL,
  `raceDate` DATE NOT NULL,
  `raceTimeUTC` TIME NULL,
  `raceName` VARCHAR(100) NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `creator_idx` (`createdBy` ASC) VISIBLE,
  INDEX `circuit_idx` (`circuitID` ASC) VISIBLE,
  INDEX `weather_idx` (`weatherID` ASC) VISIBLE,
  CONSTRAINT `creator`
    FOREIGN KEY (`createdBy`)
    REFERENCES `WeatherDataStore`.`Contributer` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `circuit`
    FOREIGN KEY (`circuitID`)
    REFERENCES `WeatherDataStore`.`Circuit` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `weather`
    FOREIGN KEY (`weatherID`)
    REFERENCES `WeatherDataStore`.`Weather` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
